---
- hosts: flightdeck_db
  tasks:
    - name: Create a temp directory
      tempfile:
        state: directory
        prefix: "docker-cmd-"
      register: _cmd_temp_dir
      notify:
        - delete temp items

    - name: Get a list of database table counts
      community.mysql.mysql_query:
        query: >
          select table_schema, count(*) as table_count
            from tables
           where table_type = %s
             and table_schema in %s
        positional_args:
          - "BASE TABLE"
          - "{{ mysql_databases | map(attribute='name') | list | default([]) }}"
        login_db: "information_schema"
        login_user: "root"
        login_unix_socket: "/var/run/mysqld/mysqld.sock"
        config_file: "/var/lib/mysql/.my.cnf"
      register: _table_counts

    - name: Reduce that list to only populated databases
      set_fact:
        _populated_dbs: "{{ _table_counts | json_query(_query) | list }}"
      vars:
        _query: "query_result[0][?table_count > `0`].table_schema"

  handlers:
    - name: delete temp items
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - "{{ _cmd_temp_dir.path }}"
